/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import Modele.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cherifa azou
 */
public class GestionEnseigant extends javax.swing.JFrame {

    Connexion cn = new Connexion();
    Statement s;
    ResultSet rs;
    DefaultTableModel tab = new DefaultTableModel();

    public GestionEnseigant() {
        initComponents();
        setLocationRelativeTo(this);
        setDefaultCloseOperation(HIDE_ON_CLOSE);
        try {
            s = cn.conectBdd().createStatement();
            rs = s.executeQuery("select * from enseignant");
            //ajouter les colones au model
            tab.addColumn("identifiant");
            tab.addColumn("Nom");
            tab.addColumn("Prenom");
            tab.addColumn("Age");
            tab.addColumn("Diplome");
            while (rs.next()) {
                tab.addRow(new Object[]{rs.getObject("id"), rs.getObject("nom"),
                    rs.getObject("prenom"), rs.getObject("age"),
                    rs.getObject("diplome")});

            }
            tableenseignant.setModel(tab);
        } catch (SQLException ex) {
            Logger.getLogger(GestionEnseigant.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void select(int ligneslt) {
        tnom.setText(tableenseignant.getValueAt(ligneslt, 1) + "");
        tprenom.setText(tableenseignant.getValueAt(ligneslt, 2).toString());
        tage.setText(tableenseignant.getValueAt(ligneslt, 3).toString());
        cbdip.setSelectedItem(tableenseignant.getValueAt(ligneslt, 4));
    }

    public void reset() {
        tnom.setText(null);
        tprenom.setText(null);
        tage.setText(null);
        cbdip.setSelectedItem("Licence");
    }

    public void actualise() {
        tab.setColumnCount(0);
        tab.setRowCount(0);
        try {
            s = cn.conectBdd().createStatement();
            rs = s.executeQuery("select * from enseignant");
            //ajouter les colones au model
            tab.addColumn("identifiant");
            tab.addColumn("Nom");
            tab.addColumn("Prenom");
            tab.addColumn("Age");
            tab.addColumn("Diplome");
            while (rs.next()) {
                tab.addRow(new Object[]{rs.getObject("id"), rs.getObject("nom"),
                    rs.getObject("prenom"), rs.getObject("age"),
                    rs.getObject("diplome")});

            }
            tableenseignant.setModel(tab);
        } catch (SQLException ex) {
            Logger.getLogger(GestionEnseigant.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titre = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tage = new javax.swing.JTextField();
        tprenom = new javax.swing.JTextField();
        tnom = new javax.swing.JTextField();
        cbdip = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        bajouter = new javax.swing.JButton();
        bsupprimer = new javax.swing.JButton();
        bmodifier = new javax.swing.JButton();
        trecherche = new javax.swing.JTextField();
        brechercher = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableenseignant = new javax.swing.JTable();
        Lfond = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titre.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        titre.setForeground(new java.awt.Color(255, 255, 255));
        titre.setText("GESTION DES ENSEIGNANT");
        getContentPane().add(titre, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "veuiller reensegner les champs", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(255, 0, 0)));
        jPanel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Prenom: ");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Age:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Diplome: ");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Nom: ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));
        jPanel1.add(tage, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 170, -1));

        tprenom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tprenomFocusLost(evt);
            }
        });
        jPanel1.add(tprenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 170, -1));

        tnom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tnomFocusLost(evt);
            }
        });
        jPanel1.add(tnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 170, -1));

        cbdip.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Licence", "Master", "Doctorat" }));
        cbdip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbdipActionPerformed(evt);
            }
        });
        jPanel1.add(cbdip, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 170, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 350, 210));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mise a jour", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(255, 0, 0)));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bajouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Ajouter.png"))); // NOI18N
        bajouter.setText("Ajouter");
        bajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajouterActionPerformed(evt);
            }
        });
        jPanel2.add(bajouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 260, -1));

        bsupprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Supprimer.png"))); // NOI18N
        bsupprimer.setText("Supprimer");
        bsupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsupprimerActionPerformed(evt);
            }
        });
        jPanel2.add(bsupprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 260, -1));

        bmodifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/modifier.png"))); // NOI18N
        bmodifier.setText("Modifier");
        bmodifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmodifierActionPerformed(evt);
            }
        });
        jPanel2.add(bmodifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 260, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 330, 210));

        trecherche.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                trechercheFocusGained(evt);
            }
        });
        getContentPane().add(trecherche, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, 180, 40));

        brechercher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/rechercher.png"))); // NOI18N
        brechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brechercherActionPerformed(evt);
            }
        });
        getContentPane().add(brechercher, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, -1, -1));

        tableenseignant.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableenseignant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableenseignantMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableenseignant);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 710, 110));

        Lfond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/FondPetit.png"))); // NOI18N
        getContentPane().add(Lfond, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenu1.setText("Fichier");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("nouveau");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("quiter");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbdipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbdipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbdipActionPerformed

    private void bajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajouterActionPerformed
        if (tnom.getText().trim().isEmpty() || tprenom.getText().trim().isEmpty()
                || tage.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,"champ obligatoire ",
                    "Ereur", JOptionPane.WARNING_MESSAGE);

        } else {
            try {
                s = cn.conectBdd().createStatement();
                s.executeUpdate("insert into enseignant(nom,prenom,age,diplome) values('"
                        + tnom.getText() + "','" + tprenom.getText() 
                        + "','" + tage.getText() + "','"
                        + cbdip.getSelectedItem() + "')");
                JOptionPane.showMessageDialog(this, "Ajout fait avec succes ");
                actualise();
                reset();
            } catch (SQLException ex) {
                Logger.getLogger(GestionEnseigant.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_bajouterActionPerformed

    private void tableenseignantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableenseignantMouseClicked
        select(tableenseignant.getSelectedRow());
    }//GEN-LAST:event_tableenseignantMouseClicked

    private void tnomFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tnomFocusLost
        tnom.setText(tnom.getText().toUpperCase());

    }//GEN-LAST:event_tnomFocusLost

    private void tprenomFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tprenomFocusLost
        tprenom.setText(tprenom.getText().substring(0, 1).toUpperCase()
                + tprenom.getText().substring(1).toLowerCase());
    }//GEN-LAST:event_tprenomFocusLost

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        reset();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        int res = JOptionPane.showConfirmDialog(this, "Voullez vous vraiment quitter ?",
                "Confirmation", JOptionPane.YES_NO_OPTION);
        if (res == 0) {
            System.exit(res);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void bsupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsupprimerActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Voullez vous vraiment supprimer ?",
                "Confirmation", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            try {
                s = cn.conectBdd().createStatement();
                s.executeUpdate("delete from enseignant where id='"
                        + tableenseignant.getValueAt(tableenseignant.getSelectedRow(), 0) + "'");
                JOptionPane.showMessageDialog(this, "Suppression avec succes ");
                actualise();
                reset();
            } catch (SQLException ex) {
                Logger.getLogger(GestionEnseigant.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_bsupprimerActionPerformed

    private void bmodifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmodifierActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Voullez vous vraiment modifier ?",
                "Confirmation", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            try {
                s = cn.conectBdd().createStatement();
                s.executeUpdate("update enseignant set nom='" + tnom.getText()
                        + "',prenom='" + tprenom.getText() + "',age='" + tage.getText()
                        + "',diplome='" + cbdip.getSelectedItem() + "' where id='"
                        + tableenseignant.getValueAt(tableenseignant.getSelectedRow(), 0) + "'");
                JOptionPane.showMessageDialog(this, "Modification faite avec succes ");
                reset();
                actualise();
            } catch (SQLException ex) {
                Logger.getLogger(GestionEnseigant.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_bmodifierActionPerformed

    private void brechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brechercherActionPerformed
        try {
            s = cn.conectBdd().createStatement();
            rs = s.executeQuery("select * from enseignant where nom='"
                    + trecherche.getText() + "'");
            tab.setRowCount(0);
            while (rs.next()) {
                tab.addRow(new Object[]{rs.getObject("id"), rs.getObject("nom"),
                    rs.getObject("prenom"), rs.getObject("age"), rs.getObject("diplome")});
            }
            tableenseignant.setModel(tab);
            if (tab.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "l'enseignant n'existe pas ");
                actualise();
            } else {
                select(0);
            }
        } catch (SQLException ex) {
            Logger.getLogger(GestionEnseigant.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_brechercherActionPerformed

    private void trechercheFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_trechercheFocusGained
        trecherche.setText(null);
        actualise();
        reset();
    }//GEN-LAST:event_trechercheFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionEnseigant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionEnseigant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionEnseigant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionEnseigant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionEnseigant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lfond;
    private javax.swing.JButton bajouter;
    private javax.swing.JButton bmodifier;
    private javax.swing.JButton brechercher;
    private javax.swing.JButton bsupprimer;
    private javax.swing.JComboBox cbdip;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableenseignant;
    private javax.swing.JTextField tage;
    private javax.swing.JLabel titre;
    private javax.swing.JTextField tnom;
    private javax.swing.JTextField tprenom;
    private javax.swing.JTextField trecherche;
    // End of variables declaration//GEN-END:variables
}
